import { createSlice } from '@reduxjs/toolkit';

// Define the initial state for the video slice
const initialState = {
  videos: [],
  cart: [],
};

// Create a new slice for videos
const videoSlice = createSlice({
  name: 'video',
  initialState,
  reducers: {
    // Reducer to add a video to the cart
    addToCart(state, action) {
      const { id } = action.payload;
    if (state.cart.includes(id)) {
        // If the id is not in the cart array, push it
        state.cart = state.cart.filter((item) => item !== id);
      } else {
        state.cart = [...state.cart, id];
      }
    },
  },
});

// Export the action creators generated by createSlice
export const { addToCart } = videoSlice.actions;

// Export the reducer
export default videoSlice.reducer;
